try {
  const val = 42;
  const oopsy = 
} catch (error) {
  console.log(error);
}
